### ISSUE TITLE
Formatting month is not consistent with documentation

### ISSUE THREAD

**Issue by JasperH8g** [datejs/Datejs#10]
The docs state:

MMM    Abbreviated month name. Date.CultureInfo.abbreviatedMonthNames.              "Jan" to "Dec"
MMMM   The full month name. Date.CultureInfo.monthNames.                            "January" to "December"

While the result is the exact opposite of these two options.

**Comment by MareoRaft** [comment]
For me, both "MMM" and "MMMM" output the long version when using version 1.0 Alpha-1 directly.

I then switched to including datejs via [npm](https://www.npmjs.com/package/datejs), which installed version 1.0.0-rc3, and this fixed the issue.
