### ISSUE TITLE
Problem with adding months

### ISSUE THREAD

**Issue by PeterPan73** [datejs/Datejs#73]
Hi everyone, I have a problem with adding additional months.

var durationMonth = $('#periodId').find(':selected').data('id'); // value => 3 m
var startDate = $('#comencingDate').val(); // value -> 2015.12.14
$('#expiringDate').val(Date.parse(startDate + ' + ' + durationMonth).toString("yyyy-MM-dd")); // This return 2016-03-03, but have to return 2016-03-13

The problem is only with months, with days and years work ok. If you have any suggestion I will be very glad to hear. Thanks in advance.

**Comment by geoffreymcgill** [comment]
Hello. Can you provide a code sample that does not have dependencies on external js libraries? Just set the variables as raw strings if you are acquiring from form element or data source.

**Comment by PeterPan73** [comment]
Hi @geoffreymcgill see here http://stackoverflow.com/questions/34275998/date-js-cannot-add-months

**Comment by PeterPan73** [comment]
@geoffreymcgill any suggestion?

**Comment by geoffreymcgill** [comment]
I tried a few samples based on what I think you are doing, and they appeared to parse properly. 

If you can provide a simplified sample that demonstrates how to reproduce the problem, then I should be able to test further. 

https://github.com/datejs/Datejs/issues/73#issuecomment-164552043
