### ISSUE TITLE
Date.parse('april')

### ISSUE THREAD

**Issue by urkules** [datejs/Datejs#75]
Hi there 

I have had some issue trying to Parse dates in April. Any thing in April always comes out to 
01 April [whatever year]

I have noticed others have had similar issue I have had to start Parsing Dates `yyyy-MM-dd`
Not a major issue. but my trust in Date.JS has been shaken. 
What do I do if parsing by  `yyyy-MM-dd` starts to Not work??

**Comment by geoffreymcgill** [comment]
Can you provide a test case? a sample string that you are attempting to parse.

**Comment by urkules** [comment]
Hi Geoffrey

Many thanks for the response.

I am trying the text '28 April 2016'
But I'm getting the same result for any date in April and for the previous year too.

I tried this in both chrome and ie. And also with Uk and USA date format

Kind regards

Ian

Sent from my Windows Phone

**Comment by geoffreymcgill** [comment]
For me `Date.parse('28 April 2016');` returns the correct value.

If you know the exact format of the string, another option could be using `parseExact`.

``` javascript
Date.parseExact('28 April 2016', 'dd MMMM yyyy');
```

Hope this helps.

**Comment by urkules** [comment]
Well I did try the the web site. Quite a lot and always got the same same result

Which was why I tried all sorts of things.. Like time zones and things like that.

Never mind. Thanks for trying

I have worked round the issue by using the format yyyy-MM-dd

Strange one..

If I have a spare few hours. I'll  step through the api and let you know what I find

Kind regards Ian

Sent from my Windows Phone

**Comment by urkules** [comment]
Hi Geoffrey

if you are interested. you can have a go on the test that I have just set up

http://urksworks.mooo.com/datetest/menutest.html

please excuse the name of the file. the test was originally some thing else 

Many thanks for the suggestion. sadly I will need to find out why for only april the system fails 

also please not that I have the ALPHA-1 version posted on the site as the last release 

Kind regards

Ian 

Date: Mon, 8 Feb 2016 15:02:02 -0800

**Comment by rskumar** [comment]
`Date.parse('28 April 2015');` retuns `Wed Apr 01 2015 00:00:00 GMT+0530 (India Standard Time)`.
So 28th April is reset after parsing to 1st April.

**Comment by urkules** [comment]
I have found lots of Instances where the parse fails when using that input format.

I parse the yyyy-MM-dd format now, and it seems pretty stable
