### ISSUE TITLE
Native ECMAScript 1.5 Date.now is overwritten by date.js

### ISSUE THREAD

**Issue by bobby-driggs** [datejs/Datejs#88]
The native Date.now() function returns the number of seconds since Jan. 1st, 1970, however datejs over writes the native function, returning "new Date();" which is the UTC timestamp string. This can potentially cause unintended issues.

**Comment by bobby-driggs** [comment]
Going through, there are 3 locations where internally datejs uses its version of Date.now(). 

1) Date.today
2) Number.prototype.fromNow
3) Number.prototype.ago

Removing the Date.now overwrite, and replacing the Date.now() call in the 3 functions above with (new Date()) seems to give correct behaviour.

**Comment by Zeragamba** [comment]
I've dug through the code, and i don't see where Date.now() is used in those three functions, nor do I see an overwrite to Date.now.

Do you have a line number of where the overwrites are? I may have missed the changes.

**Comment by bobby-driggs** [comment]
You know what, after looking back through all this. I somehow did not grab the latest version, and the version with the issue is 1.0 built in Nov. 2007. It would appear the latest (built in 2008) does not have this issue! So we can close this.
