### ISSUE TITLE
How to convert to readable format

### ISSUE THREAD

**Issue by dsgill** [datejs/Datejs#91]
I have date values of the format 180314120000Z. I need to convert them to strings of the format yyyy-MM-dd HH:mm:ssZ.

How would I use your library to easily do that? Thank you.

**Comment by geoffreymcgill** [comment]
Hi @dsgill - What is `180314120000`? Number of milliseconds since 1970-01-01?

**Comment by dsgill** [comment]
Yes I believe it is.

**Comment by dsgill** [comment]
Sorry, my mistake. It's ASN1_TIME. Format is YYMMDDHHmmSSZ.
