### ISSUE TITLE
getweek wrong value

### ISSUE THREAD

**Issue by iamxor** [datejs/Datejs#94]
Hey
var cd = Date.parse('1/1/2017');
currentWeekNo = cd.getWeek();

currentWeekNo is 52 wtf?

**Comment by geoffreymcgill** [comment]
Yes, that is the correct, and expected result.

**Comment by iamxor** [comment]
01/01/2017 is an first week of an year what am doing wrong?

**Comment by geoffreymcgill** [comment]
Based on what standard are you determining that?

**Comment by iamxor** [comment]
Based on russian culture. How do i switch?

**Comment by geoffreymcgill** [comment]
2017-01-01 sometimes falls in the first week of the year. In 2017, it does not. Culture/Country doesn't matter.

**Comment by iamxor** [comment]
on a c#
same date
DateTimeFormatInfo dfi = new CultureInfo("ru-RU").DateTimeFormat;
DateTime date1 = new DateTime(2017, 1, 1);
Calendar cal = dfi.Calendar;
Console.WriteLine(cal.GetWeekOfYear(date1, CalendarWeekRule.FirstDay, DayOfWeek.Monday).ToString());

returns 1

**Comment by iamxor** [comment]
Even
            DateTimeFormatInfo dfi = new CultureInfo("en-EN").DateTimeFormat;
            DateTime date1 = new DateTime(2017, 1, 1);
            Calendar cal = dfi.Calendar;
            Console.WriteLine(cal.GetWeekOfYear(date1, dfi.CalendarWeekRule, dfi.FirstDayOfWeek).ToString());
            Console.ReadLine();

returns 1

**Comment by iamxor** [comment]
52 correct for 2016 year but for 2017 it's incorrect

**Comment by geoffreymcgill** [comment]
The ISO 8601 Week Date formula is used to calculate the week number.

https://en.wikipedia.org/wiki/ISO_week_date

> Weeks start with Monday. Each week's year is the Gregorian year in which the Thursday falls. The first week of the year, hence, always contains 4 January.

http://www.epochconverter.com/weeks/2017

If .NET is returning the wrong value, you can bring that up with their technical support. 

Hope this helps.

**Comment by iamxor** [comment]
U don t understand that your lib wrong!
And the reason why i'll stop using it

**Comment by geoffreymcgill** [comment]
Hi @iamxor – Thanks for the feedback, but `getWeek` is returning the correct value.
