### ISSUE TITLE
Extras.js usage

### ISSUE THREAD

**Issue by Vidzz** [datejs/Datejs#95]
How should the functions of Extras.js be used in the code. Should the file be required?
When I tried to use the `Date.strtotime("04/13/08")`, I get the error as: 

```js
TypeError: Date.strtotime is not a function
```

**Comment by geoffreymcgill** [comment]
I ran your sample in the browser console at http://datejs.com/test/, and it appears to function correctly. 

The *extras.js* file is loaded into that page.
